
<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Teste Inserir novo mapa no formato malha logistica</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-6">
                    <form id="form_mapa">
                        <label>
                            Nome:
                            <input type="text" name="nome" value="Mapa 1">
                        </label>
                        <br>
                        <label>
                            Mapa:
                            <textarea rows="10" name="mapa">A B 10
B D 15
A C 20
C D 30
B E 50
D E 30</textarea>
                        </label>
                        <br>
                        <input type="submit" value="Enviar">
                    </form>
                </div>
                <div class="col-md-6">
                    <h4>Resultado:</h4>
                        <pre id="resultado_mapa">...</pre>
                </div>
                <div class="col-md-6">
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Consulta de rota e melhor custo</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-6">
                    <form id="form_rota">
                        <label>
                            Origem (string):
                            <input type="text" name="origem" value="A">
                        </label>
                        <br>
                        <label>
                            Destino (string):
                            <input type="text" name="destino" value="D">
                        </label>
                        <br>
                        <label>
                            Autonomia (float):
                            <input type="text" name="autonomia" value="10">
                        </label>
                        <br>
                        <label>
                            Valor do litro (float):
                            <input type="text" name="valor_litro" value="2.50">
                        </label>
                        <br>
                        <input type="submit" value="Enviar">
                    </form>
                </div>
                <div class="col-md-6">
                    <h4>Resultado:</h4>
                    <pre id="resultado_rota">...</pre>
                </div>
                <div class="col-md-6">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h1>Documentação</h1>

        <h3>Informações</h3>
        <p>Este webservice permite o cadastro de mapas (utilizando o formato malha logística) e consulta de rotas com o melhor custo.</p>
        <i>*obs: Este webservice foi desenvolvidor para teste e não deve ser utilizado em produção.</i>

        <h3>Como Instalar</h3>
        <p>A execução padrão esta com o banco de dados SQLITE, mas pode ser migrado facilmente para qualquer banco de dados suportado pela linguagem PHP.</p>
        <ol>
            <li>Executar a linha de comando: `php composer.phar install` para instalar as dependências via composer.</li>
            <li>Executar a linha de comando `touch data/database.sqlite` para criar o bando de dados</li>
            <li>Executar a linha de comando `vendor/bin/doctrine-module orm:schema-tool:update --force` para que o doctrine implemente as tabelas do banco de dados</li>
            <li>
                Executar um servidor web, com suporte php, de sua preferência:
            </li>
        </ol>

        <h3>Padrão Utilizado</h3>
        <p>O webservice Walmart Entrega utilizam o padrão <em>REST</em> e o formato <em>JSON</em> codificado em <em>UTF-8</em> para expor os recursos disponíveis.</p>

        <h3>Como testar requisições POST, PUT, etc..</h3>
        <p>
            Para os webservices que são acessíveis via POST, como o webservice de cadastro de novos mapas e consulta de rotas por exemplo, aconselhamos a utilização de alguma das ferramentas abaixo para simular o post:



        </p>
        <ul>
            <li>Fiddler (<a href="http://www.fiddler2.com" target="_blank">http://www.fiddler2.com</a>)</li>
            <li>Poster (<a href="https://addons.mozilla.org/pt-BR/firefox/addon/2691" target="_blank">https://addons.mozilla.org/pt-BR/firefox/addon/2691</a>) - plugin para Firefox</li>
        </ul>

        <h3>Como cadastrar novo mapa</h3>
        <p>POST: http://DOMINIO/api/mapa</p>
        <stron>Parametros:</stron>
        <pre>
            {
                "nome": "Mapa de Exemplo",
                "mapa": "A B 10\nB D 15\nA C 20\nC D 30\nB E 50\nD E 30"
            }
        </pre>
        <stron>Retorno:</stron>
        <pre>
            {
                "status": "success",
                "message": ""
            }
        </pre>

        <h3>Consultar a rota com o melhor custo</h3>
        <p>POST: http://DOMINIO/api/rota</p>
        <stron>Parametros:</stron>
        <pre>
            {
                "origem": "A",
                "destino": "B",
                "autonomia": 10,
                "valor_litro": 2.5
            }
        </pre>
        <stron>Retorno:</stron>
        <pre>
            {
                "rota": "A B D",
                "custo": 6.25,
                "status": "success",
                "message": ""
            }
        </pre>
    </div>
</div>


<script>

    $(document).ready(function(){
        $('#form_mapa').submit(function(e){
            e.preventDefault();

            var data = $(this).serialize();

            $.ajax({
                type: "POST",
                url: 'api/mapa',
                data: data,
                success: function(data){
                    $('#resultado_mapa').html(JSON.stringify(data));
                    console.log(data);
                },
                dataType: 'json'
            });
        });

        $('#form_rota').submit(function(e){
            e.preventDefault();

            var data = $(this).serialize();

            $.ajax({
                type: "POST",
                url: 'api/rota',
                data: data,
                success: function(data){
                    $('#resultado_rota').html(JSON.stringify(data));
                    console.log(data);
                },
                dataType: 'json'
            });
        });
    });
</script>
